---
sidebar: sidebar 
permalink: task-blob-enable-data-services.html 
keywords: blob storage, blob working environment, azure blob storage accounts, azure blob working environment 
summary: BlueXP에서 Azure Blob 저장소 계정을 발견한 후에는 NetApp 데이터 서비스를 사용하여 백업, 계층화 및 데이터 동기화를 수행할 수 있습니다. 
---
= Azure Blob 저장소에서 NetApp 데이터 서비스 사용
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP에서 Azure Blob 저장소 계정을 발견한 후에는 NetApp 데이터 서비스를 사용하여 백업, 계층화 및 데이터 동기화를 수행할 수 있습니다.

* BlueXP 백업 및 복구 * 를 사용하여 온프레미스 ONTAP 및 Cloud Volumes ONTAP 시스템에서 Azure Blob 저장소로 데이터를 백업할 수 있습니다.
+
시작하려면 Canvas로 이동하여 Azure Blob 저장소 작업 환경의 온-프레미스 ONTAP 또는 Cloud Volumes ONTAP 작업 환경을 끌어다 놓습니다.

+
https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html["ONTAP 데이터를 Azure Blob 저장소에 백업하는 방법에 대해 자세히 알아보십시오"^].

* BlueXP 계층화 * 를 사용하여 사내 ONTAP 클러스터에서 Azure Blob 스토리지까지 비활성 데이터를 계층화할 수 있습니다.
+
시작하려면 Canvas로 이동하여 Azure Blob 저장소 작업 환경의 온-프레미스 ONTAP 작업 환경을 끌어다 놓습니다.

+
https://docs.netapp.com/us-en/bluexp-tiering/task-tiering-onprem-azure.html["ONTAP 데이터를 Azure Blob 저장소에 계층화하는 방법에 대해 자세히 알아보십시오"^].

* BlueXP 복사 및 동기화 * 를 사용하여 Azure Blob 저장소 계정 간에 데이터를 동기화할 수 있습니다.
+
시작하려면 Canvas로 이동하여 대상 작업 환경에 소스 작업 환경을 끌어다 놓습니다. Azure Blob 저장소 작업 환경은 소스 또는 타겟이 될 수 있습니다.

+
또한 Azure Blob 저장소 작업 환경을 선택하고 서비스 패널에서 * 복사 및 동기화 * 를 클릭하여 Azure Blob 저장소 계정과 데이터를 동기화할 수 있습니다.

+
https://docs.netapp.com/us-en/bluexp-copy-sync/concept-cloud-sync.html["BlueXP 복사 및 동기화 서비스에 대해 자세히 알아보십시오"^].


